quick: quick_sort.c
	gcc -o quick quick_sort.c

merge: merge_sort.c
	gcc -o merge merge_sort.c

bubble: bubble_sort.c
	gcc -o bubble bubble_sort.c

insertion: insertion_sort.c
	gcc -o insertion insertion_sort.c

selection: selection_sort.c
	gcc -o selection selection_sort.c

clean:
	rm -f quick merge bubble insertion selection