bogo: bogo_sort.c common.c
	gcc -o bogo bogo_sort.c common.c

bubble: bubble_sort.c common.c
	gcc -o bubble bubble_sort.c common.c

merge: merge_sort.c common.c
	gcc -o merge merge_sort.c common.c

quick: quick_sort.c common.c
	gcc -o quick quick_sort.c common.c

stalin: stalin_sort.c common.c
	gcc -o stalin stalin_sort.c common.c

clean:
	rm -f quick merge bogo stalin a.out